### ISSUE TITLE
IO error after failed https connection

### ISSUE THREAD

**Issue by blindpet** [desgyz/MultiMonit#1]
Getting this trace exception after trying to add a monit url, program won't start anymore

```
root@htpcguides:/opt/MultiMonit# python run.py
[14/Feb/2016:08:53:05] ENGINE Bus STARTING
CherryPy Checker:
The Application mounted at '/Home' has an empty config.

[14/Feb/2016:08:53:05] ENGINE Started monitor thread '_TimeoutMonitor'.
[14/Feb/2016:08:53:06] ENGINE Serving on http://0.0.0.0:3005
[14/Feb/2016:08:53:06] ENGINE Bus STARTED
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/MultiMonit/models/logger.py", line 31, in log
    monit = ET.parse(urllib.urlopen(m)) or ET.parse(m)
  File "/usr/lib/python2.7/urllib.py", line 86, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 207, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 436, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 958, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 818, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 780, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1165, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib/python2.7/ssl.py", line 381, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 143, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [Errno 104] Connection reset by peer
```

**Comment by audibailey** [comment]
Please manually delete the config.ini file located in the root of the install directory and try the web setup again, the error is from the link you typed in during setup. I am working on Fixing error handling, UI errors and adding settings this coming update.

**Comment by audibailey** [comment]
New release fixed this issue.
